### ISSUE TITLE
Desired outputs?

### ISSUE THREAD

**Issue by mattjshannon** [PAHdb/pyPAHdb#3]
The example will currently create a PDF of the resulting fit to the sample data. We should make a list of what quantitative outputs are desireable for the user, so that they can perform quantitative analyses using our PAHdb fits.

Presumably want...
- map of relevant quantities (if a spectral map is used): e.g., size (large vs small), charge state, composition?
- perhaps a list of which molecules dominate the fit (and in what fractions)
- spectra of a certain number of species?
- maybe a histogram of size, charge, etc.

Perhaps once we have a list we could break these out into separate issues.

**Comment by PAHdb** [comment]
The output is currently all handled by the pypahdb.writer-class - which seems an appropriate place. pypahdb should be considered a *lite*-version of the full-blown *AmesPAHdbPythonSuite* and keep strictly to the promises made for the JWST ERS proposal. Some distinction should be made between spectral maps and staring observations, but these should flow naturally from how the data is read. Currently staring observations are considered single-pixel spectral maps. I envision the following outputs, where optionally a basename for the filenames is provided:

* A PDF-file summarizing the results, optionally disabled via a opdf-keyword, with:
  * A page with the observed spectrum, the total fit, the charge and size breakdown spectra, and the residual of the fit for each pixel. The figure should also show the ionized fraction, i.e., the fraction of the emission that is due to PAH cations / PAH neutrals; same for the large fraction, and the norm.
  * In case of a spectral map, also include images of the charge and size breakdown, and the norm - ideally WCS-aligned and showing ra-dec on the axis.
* A single fits-file, optionally disabled with a ofits-keyword, with:
  * In the primary image 3 planes with the ionized fraction, large fraction and norm
  * The header should contain useful information for reading the file

**Comment by PAHdb** [comment]
Pull request #8 closes this issue.
